// Code generated by stork-code-gen. DO NOT EDIT.

package keaconfig

// Attention! Generated Code!
//
// Run "rake gen:std_option_defs" to regenerate the option definitions
// specified in the "codegen/std_dhcpv6_option_def.json" using the
// template file "stdoptiondef6.go.template" into the "stdoptiondef6.go".

// Returns standard DHCPv6 option definitions generated by the
// "stork-code-gen tool".
func getStdDHCPv6OptionDefs() []dhcpOptionDefinition {
	return []dhcpOptionDefinition{
		{
			Code:        94,
			Name:        "s46-cont-mape",
			OptionType:  "empty",
			Space:       "dhcp6",
			Encapsulate: "s46-cont-mape-options",
		},
		{
			Code:        95,
			Name:        "s46-cont-mapt",
			OptionType:  "empty",
			Space:       "dhcp6",
			Encapsulate: "s46-cont-mapt-options",
		},
		{
			Code:        96,
			Name:        "s46-cont-lw",
			OptionType:  "empty",
			Space:       "dhcp6",
			Encapsulate: "s46-cont-lw-options",
		},
		{
			Code:       90,
			Name:       "s46-br",
			OptionType: "ipv6-address",
			Space:      "s46-cont-mape-options",
		},
		{
			Code:        89,
			Name:        "s46-rule",
			OptionType:  "record",
			Space:       "s46-cont-mape-options",
			Encapsulate: "s46-rule-options",
			RecordTypes: []DHCPOptionType{
				"uint8", "uint8", "uint8", "ipv4-address", "ipv6-prefix",
			},
		},
		{
			Code:        89,
			Name:        "s46-rule",
			OptionType:  "record",
			Space:       "s46-cont-mapt-options",
			Encapsulate: "s46-rule-options",
			RecordTypes: []DHCPOptionType{
				"uint8", "uint8", "uint8", "ipv4-address", "ipv6-prefix",
			},
		},
		{
			Code:       91,
			Name:       "s46-dmr",
			OptionType: "ipv6-prefix",
			Space:      "s46-cont-mapt-options",
		},
		{
			Code:       90,
			Name:       "s46-br",
			OptionType: "ipv6-address",
			Space:      "s46-cont-lw-options",
		},
		{
			Code:        92,
			Name:        "s46-v4v6bind",
			OptionType:  "record",
			Space:       "s46-cont-lw-options",
			Encapsulate: "s46-v4v6bind-options",
			RecordTypes: []DHCPOptionType{
				"ipv4-address", "ipv6-prefix",
			},
		},
		{
			Code:       93,
			Name:       "s46-portparams",
			OptionType: "record",
			Space:      "s46-rule-options",
			RecordTypes: []DHCPOptionType{
				"uint8", "psid",
			},
		},
		{
			Code:       93,
			Name:       "s46-portparams",
			OptionType: "record",
			Space:      "s46-v4v6bind-options",
			RecordTypes: []DHCPOptionType{
				"uint8", "psid",
			},
		},
	}
}
