image: registry.gitlab.isc.org/isc-projects/stork/ci-base:9

# Only create pipelines for merge requests and pushes/merges to the main branch
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME =~ /^stork_v[0-9]+_[0-9]+$/)'

variables:
  POSTGRES_ADDR: postgres:5432
  POSTGRES_DB: storktest
  POSTGRES_USER: storktest
  POSTGRES_PASSWORD: storktest
  STORK_DATABASE_MAINTENANCE_NAME: "postgres"
  STORK_DATABASE_MAINTENANCE_USER_NAME: "storktest"
  STORK_DATABASE_MAINTENANCE_PASSWORD: "storktest"

  # this is used to build docker images of stork (using DIND)
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""  # this is workaround for TLS problem https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/

  # Force Unicode
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

  # The hooks are specified as the git submodules. It allows us to pin the
  # specific commit to release. It is beneficial as the hook development may
  # not be in sync with the main project development.
  # The hooks are not needed in the most of CI tasks, so the repositories are
  # not cloned by default.
  GIT_SUBMODULE_STRATEGY: none

  # SLSA - enable artifact provenance metadata
  RUNNER_GENERATE_ARTIFACTS_METADATA: "true"

  # Download Python packages to cached location.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/tools/python/pip_cache"

  # Only pull the cache by default in all the jobs.
  CACHE_POLICY: pull


default:
  # AWS can interrupt the spot instance anytime, so let's retry the job when
  # the interruption event happens to avoid a pipeline failure.
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# stages order
stages:
  - cache # this stage is used to automatically rebuild and push cache for MR branch or for the master branch
  - build
  - checks
  - hooks
  - deploy

#############################################################################
### job templates and YAML anchors with content to be used in many places ###
#############################################################################
# expression which evaluates to true only when pipeline source is a push to master (MR merge to master)
.is_push_to_master: &is_push_to_master
  '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'

# expression which evaluates to true only when pipeline source is a push to master (MR merge to master) or a git tag push
.is_push_to_master_or_tag: &is_push_to_master_or_tag
  '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME =~ /^stork_v[0-9]+_[0-9]+$/)'

# expression which evaluates to true only when pipeline source is a merge request event (push to MR branch)
.is_mr_event: &is_mr_event
  '$CI_PIPELINE_SOURCE == "merge_request_event"'

# default job template to be used in all jobs
.job_template: &job_template
  tags:
    - linux
    - aws
    - runner-manager
    - amd64

# template setting appropriate tags for ARM (aarch64) architecture jobs
.job_template_arm: &job_template_arm
  tags:
    - linux
    - aws
    - runner-manager
    - aarch64

# template with alpine image
.image_alpine: &image_alpine
  image: registry.gitlab.isc.org/isc-projects/stork/pkgs-alpine:13
  variables:
    # CGO is disabled by default in official images from Go 1.23.
    CGO_ENABLED: 1

# template with redhat image
.image_redhat: &image_redhat
  image: registry.gitlab.isc.org/isc-projects/stork/pkgs-redhat-ubi:9

# template with debian image
.image_debian: &image_debian
  image: ruby:3.3.5-bullseye

# rule to run the job only when it is manually triggered; to be used in "rules"
.rule_manual_allow_failure: &rule_manual_allow_failure
  when: manual
  allow_failure: true # if manual job is not triggered, allow to fail to not block the pipeline

### caches templates ###
.golang_cache_paths: &golang_cache_paths
  paths:
    - tools/golang
  policy: $CACHE_POLICY

.python_cache_paths: &python_cache_paths
  paths:
    - tools/python
  policy: $CACHE_POLICY

.nodejs_cache_paths: &nodejs_cache_paths
  paths:
    - tools/nodejs
  policy: $CACHE_POLICY

# For all below cache templates, the default cache key is using MR branch name as suffix.
# In case cache for MR branch doesn't exist, there is a fallback to "master/main" branch cache.
.golang_cache: &golang_cache
  key: golang_amd64-$CI_COMMIT_REF_SLUG
  <<: *golang_cache_paths
  fallback_keys:
    - golang_amd64-$CI_DEFAULT_BRANCH

.golang_arm_cache: &golang_arm_cache
  key: golang_arm64-$CI_COMMIT_REF_SLUG
  <<: *golang_cache_paths
  fallback_keys:
    - golang_arm64-$CI_DEFAULT_BRANCH

.golang_cache_alpine: &golang_cache_alpine
  key: golang_amd64_alpine-$CI_COMMIT_REF_SLUG
  <<: *golang_cache_paths
  fallback_keys:
    - golang_amd64_alpine-$CI_DEFAULT_BRANCH

.golang_arm_cache_alpine: &golang_arm_cache_alpine
  key: golang_arm64_alpine-$CI_COMMIT_REF_SLUG
  <<: *golang_cache_paths
  fallback_keys:
    - golang_arm64_alpine-$CI_DEFAULT_BRANCH

.nodejs_cache: &nodejs_cache
  key: nodejs_amd64-$CI_COMMIT_REF_SLUG
  <<: *nodejs_cache_paths
  fallback_keys:
    - nodejs_amd64-$CI_DEFAULT_BRANCH

.nodejs_arm_cache: &nodejs_arm_cache
  key: nodejs_arm64-$CI_COMMIT_REF_SLUG
  <<: *nodejs_cache_paths
  fallback_keys:
    - nodejs_arm64-$CI_DEFAULT_BRANCH

.python_cache: &python_cache
  key: python_amd64-$CI_COMMIT_REF_SLUG
  <<: *python_cache_paths
  fallback_keys:
    - python_amd64-$CI_DEFAULT_BRANCH

.python_arm_cache: &python_arm_cache
  key: python_arm64-$CI_COMMIT_REF_SLUG
  <<: *python_cache_paths
  fallback_keys:
    - python_arm64-$CI_DEFAULT_BRANCH

.python_cache_alpine: &python_cache_alpine
  key: python_amd64_alpine-$CI_COMMIT_REF_SLUG
  <<: *python_cache_paths
  fallback_keys:
    - python_amd64_alpine-$CI_DEFAULT_BRANCH

.python_arm_cache_alpine: &python_arm_cache_alpine
  key: python_arm64_alpine-$CI_COMMIT_REF_SLUG
  <<: *python_cache_paths
  fallback_keys:
    - python_arm64_alpine-$CI_DEFAULT_BRANCH

.python_cache_redhat: &python_cache_redhat
  key: python_amd64_redhat-$CI_COMMIT_REF_SLUG
  <<: *python_cache_paths
  fallback_keys:
    - python_amd64_redhat-$CI_DEFAULT_BRANCH

.python_arm_cache_redhat: &python_arm_cache_redhat
  key: python_arm64_redhat-$CI_COMMIT_REF_SLUG
  <<: *python_cache_paths
  fallback_keys:
    - python_arm64_redhat-$CI_DEFAULT_BRANCH

.playwright_browsers_cache: &playwright_browsers_cache
  key: playwright_browsers-$CI_COMMIT_REF_SLUG
  paths:
    - tools/playwright_browsers
  policy: $CACHE_POLICY
  fallback_keys:
    - playwright_browsers-$CI_DEFAULT_BRANCH

####################################################################################
### STAGE cache                                                                  ###
####################################################################################

### common parts used in stage jobs ###
# template to be used by all jobs in the stage
.cache_job_template: &cache_job_template
  <<: *job_template
  stage: cache
  variables:
    CACHE_POLICY: push

# Below job templates are designed to be run automatically:
# 1. if source of the pipeline was push to MR branch event AND any of the files listed
#    under the "changes:paths" changed comparing to the previous commit in MR branch
# 2. if source of the pipeline was push to "master/main" branch event AND any of the files listed
#    under the "changes:paths" changed comparing to the previous HEAD of "master/main" branch
#
# This way, cache for the MR branch will be created only when the MR is touching any file under "changes:paths".
# Usual MR pipeline will not trigger this action and will be using a fallback cache built for "master/main" branch.
# When MR is merged to "master/main" branch, and it changed any file under "changes:paths",
# the cache for "master/main" branch will be rebuilt automatically.
#
# All "rebuild_cache" jobs can also be triggered manually.

# job template for rebuilding cache for default debian image
.cache_job_template_debian: &cache_job_template_debian
  <<: *cache_job_template
  rules:
    - if: *is_mr_event
      changes:
        paths:
          - backend/go.mod
          - backend/go.sum
          - webui/package.json
          - webui/package-lock.json
          - rakelib/**/*
        compare_to: "$CI_COMMIT_REF_SLUG~1" # compares files under the "changes:paths" against previous commit in MR branch
    - if: *is_push_to_master
      changes:
        paths:
          - backend/go.mod
          - backend/go.sum
          - webui/package.json
          - webui/package-lock.json
          - rakelib/**/*
    - *rule_manual_allow_failure

# job template for rebuilding cache for alpine image
.cache_job_template_alpine: &cache_job_template_alpine
  <<: *cache_job_template
  <<: *image_alpine
  variables:
    # CGO is disabled by default in official images from Go 1.23.
    CGO_ENABLED: 1
    CACHE_POLICY: push
    # The submodules are not included in the artifacts even if the `untracked`
    # option is set. It is a bug in GitLab: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2457
    # We clone the fresh copy of the submodules. As long as our hooks need only
    # Golang to compile, it shouldn't be a problem.
    GIT_SUBMODULE_STRATEGY: normal
  rules:
    - if: *is_mr_event
      changes:
        paths:
          - backend/go.mod
          - backend/go.sum
          - rakelib/**/*
        compare_to: "$CI_COMMIT_REF_SLUG~1" # compares files under the "changes:paths" against previous commit in MR branch
    - if: *is_push_to_master
      changes:
        paths:
          - backend/go.mod
          - backend/go.sum
          - rakelib/**/*
    - *rule_manual_allow_failure

  script:
    - rake prepare:dist
    - rake prepare:deps
    - rake hook:update_deps

# job template for rebuilding cache for redhat image
.cache_job_template_redhat: &cache_job_template_redhat
  <<: *cache_job_template
  <<: *image_redhat
  rules:
    - if: *is_mr_event
      changes:
        paths:
          - rakelib/**/*
        compare_to: "$CI_COMMIT_REF_SLUG~1" # compares files under the "changes:paths" against previous commit in MR branch
    - if: *is_push_to_master
      changes:
        paths:
          - rakelib/**/*
    - *rule_manual_allow_failure

  script:
    - rake prepare:doc_deps

### jobs definitions ###
# rebuilds debian caches only when needed
rebuild_cache_amd64:
  <<: *cache_job_template_debian
  cache:
    - *golang_cache
    - *python_cache
    - *nodejs_cache
    - *playwright_browsers_cache
  script:
    - rake prepare
    - rake prepare:dev
    - rake prepare:deps
    - rake hook:prepare
    - rake hook:update_deps

# rebuilds debian ARM caches only when needed
rebuild_cache_arm64:
  <<: *cache_job_template_debian
  <<: *job_template_arm
  cache:
    - *golang_arm_cache
    - *python_arm_cache
    - *nodejs_arm_cache
  script:
    - rake prepare
    - rake prepare:deps
    - rake hook:prepare
    - rake hook:update_deps

# rebuilds alpine caches only when needed
rebuild_cache_amd64_alpine:
  <<: *cache_job_template_alpine
  cache:
    - *golang_cache_alpine
    - *python_cache_alpine

# rebuilds alpine ARM caches only when needed
rebuild_cache_arm64_alpine:
  <<: *cache_job_template_alpine
  <<: *job_template_arm
  cache:
    - *golang_arm_cache_alpine
    - *python_arm_cache_alpine

# rebuilds redhat caches only when needed
rebuild_cache_amd64_redhat:
  <<: *cache_job_template_redhat
  cache:
    - *python_cache_redhat

# rebuilds redhat ARM caches only when needed
rebuild_cache_arm64_redhat:
  <<: *cache_job_template_redhat
  <<: *job_template_arm
  cache:
    - *python_arm_cache_redhat

####################################################################################
### STAGE build                                                                  ###
####################################################################################

### common parts used in stage jobs ###
# template to be used by all jobs in the stage
.build_template: &build_template
  <<: *job_template
  stage: build

### jobs definitions ###
# This job is created so it can be used in "needs" rules by jobs that depend on cache
# and that are in following stages after the "build" stage. Thanks to this, these jobs
# will wait for rebuilding the cache only when any "cache" stage job was started.
# In case no "cache" stage job was started, jobs will run once "wait_for_cache" is finished.
# This is a workaround for needs:optional, which doesn't work for manual jobs that were not triggered (such jobs are blocked).
wait_for_cache:
  <<: *build_template
  script: ":" # no-op in the script stage in this job

build_ui:
  <<: *build_template
  cache:
    - *nodejs_cache
    - *golang_cache
    - *python_cache
  script:
    - rake build:ui
  artifacts:
    name: "ui"
    expire_in: 1 week
    paths:
      - webui/dist/stork/

build_doc:
  <<: *build_template
  cache:
    - *python_cache
  script:
    - rake build:doc
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  artifacts:
    name: "doc"
    expire_in: 1 week
    paths:
      - doc/build/

build_backend_amd64:
  <<: *build_template
  cache:
    - *golang_cache
    - *nodejs_cache ## because npm yamlinc is used
  script:
    - rake build:backend
  artifacts:
    untracked: true
    expire_in: 1 hour

build_backend_arm64:
  extends: build_backend_amd64
  <<: *job_template_arm
  cache:
    - *golang_arm_cache
    - *nodejs_arm_cache ## because npm yamlinc is used
  variables:
    ARCH: arm64

build_backend_legacy_amd64:
  <<: *build_template
  # Use image based on Debian 11. It is required to build the binaries with
  # the older GLIBC version.
  <<: *image_debian
  needs:
    - build_backend_amd64
  script:
    - rake rebuild:backend SUPPRESS_PREREQUISITES=true
  artifacts:
    name: "backend"
    expire_in: 1 week
    paths:
      - backend/cmd/stork-agent/stork-agent
      - backend/cmd/stork-server/stork-server
      - backend/cmd/stork-tool/stork-tool

build_backend_legacy_arm64:
  extends: build_backend_legacy_amd64
  <<: *job_template_arm
  needs:
    - build_backend_arm64
  variables:
    ARCH: arm64

tarball:
  <<: *build_template
  needs: [ ] # this job doesn't need cache, so it can start right away
  script:
    - rake release:tarball
  artifacts:
    paths:
      - stork-*.tar.gz
    expire_in: 1 week

build_debs_amd64:
  <<: *build_template
  cache:
    - *golang_cache
    - *python_cache
    - *nodejs_cache
  needs:
    # Use the binaries compiled by the legacy image.
    - build_backend_legacy_amd64
  script:
    - rake build:agent_pkg SUPPRESS_PREREQUISITES=true
    - rake build:server_pkg SUPPRESS_PREREQUISITES=true
    - cp dist/pkgs/*.deb ./
  artifacts:
    paths:
      - isc-stork-*.deb
    expire_in: 1 hour

build_debs_arm64:
  extends: build_debs_amd64
  <<: *job_template_arm
  cache:
    - *golang_arm_cache
    - *python_arm_cache
    - *nodejs_arm_cache
  needs:
    # Use the binaries compiled by the legacy image.
    - build_backend_legacy_arm64

build_rpms_amd64:
  <<: *build_template
  <<: *image_redhat
  cache:
    - *golang_cache
    - *python_cache_redhat
    - *nodejs_cache
  needs:
    # Use the binaries compiled by the legacy image.
    - build_backend_legacy_amd64
  script:
    - rake build:agent_pkg SUPPRESS_PREREQUISITES=true
    - rake build:server_pkg SUPPRESS_PREREQUISITES=true
    - cp dist/pkgs/*.rpm ./
  artifacts:
    paths:
      - isc-stork-*.rpm
    expire_in: 1 hour

build_rpms_arm64:
  extends: build_rpms_amd64
  <<: *job_template_arm
  cache:
    - *golang_arm_cache
    - *python_arm_cache_redhat
    - *nodejs_arm_cache
  needs:
    # Use the binaries compiled by the legacy image.
    - build_backend_legacy_arm64

build_apks_amd64:
  <<: *build_template
  <<: *image_alpine
  cache:
    - *golang_cache_alpine
    - *python_cache_alpine
    - *nodejs_cache
  script:
    - rake build:agent_pkg
    - rake build:server_pkg
    - cp dist/pkgs/*.apk ./
  artifacts:
    paths:
      - isc-stork-*.apk
    expire_in: 1 hour

build_apks_arm64:
  extends: build_apks_amd64
  <<: *job_template_arm
  cache:
    - *golang_arm_cache_alpine
    - *python_arm_cache_alpine
    - *nodejs_arm_cache

packages:
  <<: *build_template
  rules:
    - if: *is_push_to_master_or_tag
    - *rule_manual_allow_failure
  needs:
    - build_debs_amd64
    - build_debs_arm64
    - build_rpms_amd64
    - build_rpms_arm64
    - build_apks_amd64
    - build_apks_arm64
  script:
    - ":"
  artifacts:
    paths:
      - isc-stork-*
    expire_in: 1 week

####################################################################################
### STAGE checks                                                                 ###
####################################################################################

### common parts used in stage jobs ###
# template to be used by all jobs in the stage
.checks_template: &checks_template
  <<: *job_template
  stage: checks
  needs:
    - wait_for_cache # by default, wait until all jobs in "cache" stage are finished

### jobs definitions ###
lint_backend:
  <<: *checks_template
  cache:
    - *golang_cache
    - *nodejs_cache
  script:
    - rake lint:backend

lint_changelog:
  <<: *checks_template
  needs: [ ] # this job doesn't need cache, so it can start right away
  script:
    - rake lint:changelog

lint_python_pylint:
  <<: *checks_template
  cache:
    - *python_cache
    - *nodejs_cache
    - *golang_cache
  script:
    - rake lint:python:pylint

lint_python_flake8:
  <<: *checks_template
  cache:
    - *python_cache
  script:
    - rake lint:python:flake8

lint_python_black:
  <<: *checks_template
  cache:
    - *python_cache
  script:
    - rake lint:python:black

unittest_backend:
  <<: *checks_template
  cache:
    - *golang_cache
  services:
    - name: postgres:18-alpine
      alias: postgres
  variables:
    # CGO is required by the race detector.
    CGO_ENABLED: 1
    PRESERVE_COVERAGE: "true"
  coverage: '/Total coverage:\s+\d+.\d+%/'
  script:
    - echo 'postgres:*:*:storktest:storktest' > ~/.pgpass
    - chmod 600 ~/.pgpass
    - rake unittest:backend
  artifacts:
    when: always
    paths:
      - backend/junit.xml
      - backend/coverage.cobertura.xml
    reports:
      junit: backend/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage.cobertura.xml

lint_ui:
  <<: *checks_template
  cache:
    - *nodejs_cache
    - *golang_cache
  script:
    - rake lint:ui

unittest_ui:
  <<: *checks_template
  cache:
    - *nodejs_cache
    - *golang_cache
    - *playwright_browsers_cache
  script:
    - rake unittest:ui
  artifacts:
    when: always
    paths:
      - webui/junit.xml
    reports:
      junit: webui/junit.xml

storybook_tests:
  <<: *checks_template
  cache:
    - *nodejs_cache
    - *golang_cache
    - *playwright_browsers_cache
  script:
    - rake unittest:storybook

danger:
  <<: *checks_template
  needs: [ ] # this job doesn't need cache, so it can start right away
  before_script:
    - export CI_MERGE_REQUEST_ID=$(git ls-remote -q origin merge-requests\*\head | grep $CI_COMMIT_SHA | sed 's/.*refs\/merge-requests\/\([0-9]*\)\/head/\1/g')
    - export CI_PROJECT_PATH=$CI_PROJECT_ID #some version of gitlab has problems with searching by project path
    - export DANGER_GITLAB_HOST=gitlab.isc.org
    - export DANGER_GITLAB_API_BASE_URL=https://gitlab.isc.org/api/v4
  script:
    - rake lint:git

lint_shell:
  <<: *checks_template
  needs: [ ] # this job doesn't need cache, so it can start right away
  script:
    - rake lint:shell

install_debs_amd64:
  <<: *checks_template
  rules:
    - if: *is_push_to_master_or_tag
    - *rule_manual_allow_failure
  variables:
    ARCH: amd64
  script:
    - "dpkg -i isc-stork-*${ARCH}.deb"
    - "stork-agent --version"
    - "stork-server --version"
    - "stork-tool --version"
    - "dpkg -i isc-stork-*${ARCH}.deb"
    - "stork-agent --version"
    - "stork-server --version"
    - "stork-tool --version"
    - "man stork-agent > /dev/null"
    - "man stork-server > /dev/null"
    - "man stork-tool > /dev/null"
    - "dpkg -r isc-stork-agent"
    - "dpkg -r isc-stork-server"
  needs:
    - build_debs_amd64

install_debs_amd64_ubuntu_lts:
  <<: *checks_template
  rules:
    - if: *is_push_to_master_or_tag
    - *rule_manual_allow_failure
  image: ubuntu:20.04
  variables:
    ARCH: amd64
  script:
    - "dpkg -i isc-stork-*${ARCH}.deb"
    - "stork-agent --version"
    - "stork-server --version"
    - "stork-tool --version"
    - "dpkg -i isc-stork-*${ARCH}.deb"
    - "stork-agent --version"
    - "stork-server --version"
    - "stork-tool --version"
    - "man stork-agent > /dev/null"
    - "man stork-server > /dev/null"
    - "man stork-tool > /dev/null"
    - "dpkg -r isc-stork-agent"
    - "dpkg -r isc-stork-server"
  needs:
    - build_debs_amd64

install_debs_arm64:
  extends: install_debs_amd64
  <<: *job_template_arm
  variables:
    ARCH: arm64
  needs:
    - build_debs_arm64

install_rpms_amd64:
  <<: *checks_template
  <<: *image_redhat
  rules:
    - if: *is_push_to_master_or_tag
    - *rule_manual_allow_failure
  variables:
    ARCH: x86_64
  script:
    - "rpm -i isc-stork-*${ARCH}.rpm"
    - "stork-agent --version"
    - "stork-server --version"
    - "stork-tool --version"
    - "rpm -U --force isc-stork-*${ARCH}.rpm"
    - "stork-agent --version"
    - "stork-server --version"
    - "stork-tool --version"
    - "man stork-agent > /dev/null"
    - "man stork-server > /dev/null"
    - "man stork-tool > /dev/null"
    - "rpm -e isc-stork-agent"
    - "rpm -e isc-stork-server"
  needs:
    - build_rpms_amd64

install_rpms_arm64:
  extends: install_rpms_amd64
  <<: *job_template_arm
  variables:
    ARCH: aarch64
  needs:
    - build_rpms_arm64

install_apks_amd64:
  <<: *checks_template
  <<: *image_alpine
  variables:
    ARCH: x86_64
  script:
    - "apk add --no-cache --allow-untrusted isc-stork-*${ARCH}.apk"
    - "stork-agent --version"
    - "stork-server --version"
    - "stork-tool --version"
    - "apk add --no-cache --allow-untrusted isc-stork-*${ARCH}.apk"
    - "stork-agent --version"
    - "stork-server --version"
    - "stork-tool --version"
    - "man stork-agent > /dev/null"
    - "man stork-server > /dev/null"
    - "man stork-tool > /dev/null"
    - "apk del isc-stork-agent"
    - "apk del isc-stork-server"
  needs:
    - build_apks_amd64
  artifacts:
    paths:
      - core.*
    expire_in: 1 week
    when: always

install_apks_arm64:
  extends: install_apks_amd64
  <<: *job_template_arm
  variables:
    ARCH: aarch64
  needs:
    - build_apks_arm64

### system testing ###

system_test:
  <<: *checks_template
  needs: [ ] # this job doesn't need cache, so it can start right away
  services:
    - docker:dind
  rules:
    - if: *is_push_to_master_or_tag
    - *rule_manual_allow_failure
  image: registry.gitlab.isc.org/isc-projects/stork/pkgs-compose:12
  #  cache:
  #    key: $CI_PROJECT_NAME-compose-$CI_COMMIT_REF_SLUG
  #    paths:
  #      - tools/
  #    fallback_keys:
  #      - $CI_PROJECT_NAME-compose-$CI_DEFAULT_BRANCH
  before_script:
    - ip -6 route del default
    - rake prepare:systemtest
  variables:
    BIND9_VERSION: latest-stable
    KEA_VERSION: latest-stable
    # Alpine uses the libc-musl library, which isn't compatible with the NodeJS
    # binary fetched by the Rake script. Additionally, the binaries for alpine
    # are missing on the NodeJS page. We cannot use the image based on Debian
    # because it is out-of-date.
    USE_SYSTEM_NODEJS: "true"
    # It must be an alias of the docker:dind service.
    DEFAULT_MAPPED_ADDRESS: "docker"
  script:
    # - rake system_tests_ui
    - rake systemtest:build
    - rake systemtest
  artifacts:
    paths:
      - tests/system/test-results/
    exclude:
      - tests/system/test-results/**/performance-charts.html
    expire_in: 6 months
    when: always
    reports:
      junit: tests/system/test-results/junit.xml

system_test_old_stables:
  extends: system_test
  variables:
    BIND9_VERSION: old-stable
    KEA_VERSION: old-stable
    ONLY_KEA_TESTS: "true"
  script:
    - rake systemtest:build
    - rake systemtest

system_test_latest_devs:
  extends: system_test
  variables:
    BIND9_VERSION: latest-dev
    KEA_VERSION: latest-dev
    ONLY_KEA_TESTS: "true"
  script:
    - rake systemtest:build
    - rake systemtest

####################################################################################
### STAGE hooks                                                                  ###
####################################################################################

### common parts used in stage jobs ###
# template to be used by all jobs in the stage
.hooks_template: &hooks_template
  <<: *job_template
  stage: hooks
  needs:
    - wait_for_cache # by default, wait until all jobs in "cache" stage are finished

### jobs definitions ###
build_hooks_amd64:
  <<: *hooks_template
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  cache:
    - *golang_cache
  script:
    - rake hook:build
  artifacts:
    untracked: true
    expire_in: 1 hour

build_hooks_arm64:
  extends: build_hooks_amd64
  <<: *job_template_arm
  cache:
    - *golang_arm_cache
  variables:
    ARCH: arm64

build_hooks_legacy_amd64:
  <<: *hooks_template
  # Use image based on Debian 11. It is required to build the binaries with
  # the older GLIBC version.
  <<: *image_debian
  needs:
    - build_hooks_amd64
  # The submodules are not included in the artifacts even if the `untracked`
  # option is set. It is a bug in GitLab: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2457
  # We clone the fresh copy of the submodules. As long as our hooks need only
  # Golang to compile, it shouldn't be a problem.
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    # The hook:build rebuilds the binaries every time.
    - rake hook:build
  artifacts:
    paths:
      - hooks/*.so
    expire_in: 1 hour

build_hooks_legacy_arm64:
  extends: build_hooks_legacy_amd64
  <<: *job_template_arm
  needs:
    - build_hooks_arm64
  variables:
    ARCH: arm64

unittest_hooks:
  <<: *hooks_template
  cache:
    - *golang_cache
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - rake hook:unittest

tarball_hooks:
  <<: *hooks_template
  needs: [ ] # this job doesn't need cache, so it can start right away
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - rake hook:tarball
  artifacts:
    paths:
      - stork-*-*.tar.gz
    expire_in: 1 week

build_hooks_debs_amd64:
  <<: *hooks_template
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  needs:
    # Use the binaries compiled by the legacy image.
    - build_hooks_legacy_amd64
  cache:
    - *golang_cache
    - *python_cache
  script:
    - rake hook:build_pkg SUPPRESS_PREREQUISITES=true
    - cp dist/hook-pkgs/*.deb ./
  artifacts:
    paths:
      - isc-stork-*.deb
    expire_in: 1 hour

build_hooks_debs_arm64:
  extends: build_hooks_debs_amd64
  <<: *job_template_arm
  needs:
    # Use the binaries compiled by the legacy image.
    - build_hooks_legacy_arm64
  cache:
    - *golang_arm_cache
    - *python_arm_cache

build_hooks_rpms_amd64:
  <<: *hooks_template
  <<: *image_redhat
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  needs:
    # Use the binaries compiled by the legacy image.
    - build_hooks_legacy_amd64
  cache:
    - *golang_cache
    - *python_cache_redhat
  script:
    - rake hook:build_pkg SUPPRESS_PREREQUISITES=true
    - cp dist/hook-pkgs/*.rpm ./
  artifacts:
    paths:
      - isc-stork-*.rpm
    expire_in: 1 hour

build_hooks_rpms_arm64:
  extends: build_hooks_rpms_amd64
  <<: *job_template_arm
  needs:
    # Use the binaries compiled by the legacy image.
    - build_hooks_legacy_arm64
  cache:
    - *golang_arm_cache
    - *python_arm_cache_redhat

build_hooks_apks_amd64:
  <<: *hooks_template
  <<: *image_alpine
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  cache:
    - *golang_cache_alpine
    - *python_cache_alpine
  script:
    - rake hook:build_pkg
    - cp dist/hook-pkgs/*.apk ./
  artifacts:
    paths:
      - isc-stork-*.apk
    expire_in: 1 hour

build_hooks_apks_arm64:
  extends: build_hooks_apks_amd64
  <<: *job_template_arm
  cache:
    - *golang_arm_cache_alpine
    - *python_arm_cache_alpine

packages_hooks:
  <<: *hooks_template
  rules:
    - if: *is_push_to_master_or_tag
    - *rule_manual_allow_failure
  needs:
    - build_hooks_debs_amd64
    - build_hooks_debs_arm64
    - build_hooks_rpms_amd64
    - build_hooks_rpms_arm64
    - build_hooks_apks_amd64
    - build_hooks_apks_arm64
  script:
    - ":"
  artifacts:
    paths:
      - isc-stork-*
    expire_in: 1 week


####################################################################################
### STAGE deploy                                                                 ###
####################################################################################

### upload release notes and tarball to repo.isc.org ###

upload_to_repo:
  stage: deploy
  rules:
    - if: *is_push_to_master_or_tag
      when: manual
    - *rule_manual_allow_failure
  <<: *job_template
  needs:
    - tarball
  script:
    - eval $(ssh-agent -s)
    - echo "${REPO_SSH_PRIVATE_KEY}" | base64 -d | ssh-add -
    - ssh-keyscan repo.isc.org >> ~/.ssh/known_hosts
    - rake release:notes
    - rake release:tarball:upload HOST=storkpush@repo.isc.org TARGET=/data/shared/sweng/stork/releases
  artifacts:
    name: release-notes
    expire_in: 1 week
    paths:
      - Stork-*-ReleaseNotes.txt

upload_to_repo_hooks:
  extends: upload_to_repo
  needs:
    - tarball_hooks

### demo deploy jobs ###

deploy_demo:
  stage: deploy
  rules:
    - if: *is_push_to_master
      when: always
    - *rule_manual_allow_failure
  needs: [ ] # this job doesn't need cache, so it can start right away
  <<: *job_template
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_STORK" | base64 -d | ssh-add -
  script:
    # Print Docker info
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org docker info
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org docker version
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org docker-compose version
    # Stop all containers
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org "docker ps -q | xargs docker kill || true"
    # Force network cleanup and to make sure we have clean state do restart docker service
    # They can be replaced with docker-compose down after migration from the old demo.
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org docker container prune -f
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org docker network prune -f
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org docker volume prune -f
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org sudo systemctl restart docker
    # Copy source code
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org rm -rf deploy/*
    - scp -o StrictHostKeyChecking=no -r $PWD/* jenkins@stork.lab.isc.org:~/deploy
    # Build & Start Docker containers
    - ssh -o StrictHostKeyChecking=no jenkins@stork.lab.isc.org CS_REPO_ACCESS_TOKEN=$CS_REPO_ACCESS_TOKEN deploy/stork-demo.sh --no-prompt

### upload packages to cloudsmith.io ###

upload_packages:
  stage: deploy
  rules:
    - if: *is_push_to_master_or_tag
      when: manual
    - when: manual
      allow_failure: true
  image: registry.gitlab.isc.org/isc-projects/stork/pkgs-cloudsmith:2
  tags:
    - docker
    - linux
    - aws
    - runner-manager
    - amd64
  needs:
    - packages
  variables:
    COMPONENTS: isc-stork-server,isc-stork-agent
  script:
    - export LANG='en_US.UTF-8' LC_ALL='en_US.UTF-8'
    - rake release:packages:upload

upload_packages_hooks:
  extends: upload_packages
  needs:
    - packages_hooks
  variables:
    # TODO: Append `isc-stork-agent-hook` after a comma when any agent hook
    # will be ready.
    COMPONENTS: isc-stork-server-hook

upload_test_packages:
  extends: upload_packages
  variables:
    REPO: stork-testing

upload_test_packages_hooks:
  extends: upload_packages_hooks
  variables:
    REPO: stork-testing
