build:
  os: ubuntu-lts-latest
  tools:
    python: '3.14'
  jobs:
    pre_create_environment:
      - rake prepare:doc
formats: all
python:
  install:
    - requirements: doc/src/requirements.txt
sphinx:
  configuration: doc/user/conf.py
  fail_on_warning: true
submodules:
  include: all
  recursive: true
version: 2
