desc "Build the hook
    DEBUG - build plugins in debug mode - default: false"
task :build do
    flags = []
    if ENV["DEBUG"] == "true"
        flags.append "-gcflags", "all=-N -l"
    end

    hook_name = File.basename(Dir.getwd())
    
    build_dir = "build"
    sh "mkdir", "-p", build_dir

    output_path = File.join(build_dir, hook_name + ".so")

    sh "go", "mod", "tidy"
    sh "go", "build", *flags, "-buildmode=plugin", "-o", output_path

    size = File.size output_path
    size /= 1024.0 * 1024.0
    puts "Hook: '#{output_path}' size: #{'%.2f' % size} MiB"
end

desc "Lint the hook
    FIX - fix linting issues - default: false"
task :lint do
    sh "go", "vet"
end

desc "Run hook unit tests"
task :unittest do
    sh "go", "test", "-race", "-v", "./..." 
end