# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "danger"

gem "danger-gitlab"

gem "danger-commit_lint"

# Dependencies of danger:
gem "json"
