#!/bin/sh

set -e

if [ -e /etc/redhat-release ]; then
    # add stork-server user if does not exists
    if [ ! $(getent passwd stork-server) ]; then
        useradd --system --home-dir /var/lib/ stork-server
    fi
else
    adduser --quiet --system --group --home /var/lib/ \
            --no-create-home --disabled-password --disabled-login \
            --gecos "Stork Agent User" stork-server >/dev/null
fi
