#!/bin/sh

set -e

# create folders for storing certs and agent token,
# they should be available to owner ie. stork-agent user
home_dir=/var/lib/stork-agent
mkdir -p -m 700 $home_dir/certs
mkdir -p -m 700 $home_dir/tokens

if [ -e /etc/redhat-release ]; then
    # add stork-agent user if does not exists
    if [ ! $(getent passwd stork-agent) ]; then
        useradd --system --home-dir $home_dir stork-agent
    fi

    # add stork-agent user to named so it can read its config files
    if [ $(getent group named) ]; then
        usermod -aG named stork-agent
    fi
elif [ -x "$(command -v busybox)" ]; then
    addgroup -S stork-agent >/dev/null
    adduser -h $home_dir -D -S -H -g "Stork Agent User" -G stork-agent stork-agent >/dev/null

    # add stork-agent user to bind so it can read its config files
    if [ $(getent group bind) ]; then
        addgroup stork-agent bind
    fi
elif [ -e /bin/freebsd-version ]; then
    pw group add stork-agent || /bin/true
    pw user add -n stork-agent -c "Stork Agent User" -g stork-agent -G bind || /bin/true
else
    # add stork-agent user
    adduser --quiet --system --group --home $home_dir \
            --no-create-home --disabled-password --disabled-login \
            --gecos "Stork Agent User" stork-agent >/dev/null

    # add stork-agent user to bind so it can read its config files
    if [ $(getent group bind) ]; then
        usermod -aG bind stork-agent
    fi
fi

# change ownership of all folders and files in home dir to stork-agent user
chown -R stork-agent $home_dir
