#!/bin/sh

if [ -e /etc/redhat-release ]; then
    case "$1" in
        0) # This is a yum/dnf remove.
            userdel stork-agent >/dev/null || /bin/true
            ;;
        1)  # This is a yum/dnf upgrade.
            # do nothing
            ;;
    esac
elif [ -x "$(command -v busybox)" ]; then
    deluser stork-agent >/dev/null || /bin/true
elif [ -e /bin/freebsd-version ]; then
    pw user del stork-agent || /bin/true
else
    deluser --system stork-agent >/dev/null || /bin/true
fi
