#!/bin/sh

if [ -e /etc/redhat-release ]; then
    case "$1" in
        0) # This is a yum/dnf remove.
            systemctl disable isc-stork-agent
            systemctl stop isc-stork-agent

            # remove stork-agent from any extra groups like e.g. bind
            usermod -G "" stork-agent
            ;;
        1)  # This is a yum/dnf upgrade.
            # do nothing
            ;;
    esac
else
    if [ -x "$(command -v systemctl)" ]; then
        systemctl disable isc-stork-agent
        systemctl stop isc-stork-agent
    fi

    # remove stork-agent from any extra groups like e.g. bind
    if [ -x "$(command -v busybox)" ]; then
        groups stork-agent | xargs -n 1 | grep -v stork-agent | xargs -r -n 1 delgroup stork-agent
    elif [ -e /bin/freebsd-version ]; then
        # Do nothing
    else
        usermod -G "" stork-agent
    fi
fi
