CREATE DATABASE stork;
CREATE USER stork WITH ENCRYPTED PASSWORD 'stork123';
GRANT ALL PRIVILEGES ON DATABASE stork TO stork;
\c stork
GRANT ALL PRIVILEGES ON SCHEMA public TO stork;
CREATE EXTENSION pgcrypto;
