#!/bin/sh

case "$1" in
    0) # This is a yum/dnf remove.
        if [ "$(systemctl is-system-running)" -eq 0 ]; then
            systemctl disable isc-stork-agent
            systemctl stop isc-stork-agent
        fi

        # remove stork-agent from any extra groups like e.g. bind
        usermod -G "" stork-agent
        ;;
    1)  # This is a yum/dnf upgrade.
        # do nothing
        ;;
esac
