{
 "title": "Stork Bind DNS",
 "description": "Bind DNS Service Statistics.\r\n",
 "tags": [
  "dns",
  "bind",
  "prometheus",
  "stork"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "bind_up" }
  ]
 },
 "panels": [
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Named CPU Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(bind_process_cpu_seconds_total{instance=~\"$instance\"}[120s])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Named Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bind_process_virtual_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Virtual ({{ instance }})"
      },
      {
       "expr": "bind_process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Resident ({{ instance }})"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bind_process_max_fds{instance=~\"$instance\"}",
       "legendFormat": "Max ({{ instance }})"
      },
      {
       "expr": "bind_process_open_fds{instance=~\"$instance\"}",
       "legendFormat": "Open ({{ instance }})"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal{instance=~\"$instance\"} - (node_memory_MemFree{instance=~\"$instance\"} + node_memory_Buffers{instance=~\"$instance\"} + node_memory_Cached{instance=~\"$instance\"})",
       "legendFormat": "Used ({{ instance }})"
      },
      {
       "expr": "node_memory_MemFree{instance=~\"$instance\"}",
       "legendFormat": "Free ({{ instance }})"
      },
      {
       "expr": "node_memory_Buffers{instance=~\"$instance\"}",
       "legendFormat": "Buffers ({{ instance }})"
      },
      {
       "expr": "node_memory_Cached{instance=~\"$instance\"}",
       "legendFormat": "Cached ({{ instance }})"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bind_incoming_queries_total{instance=~\"$instance\"}[120s])",
       "legendFormat": "{{ type }}  ({{ instance }})"
      }
     ]
    },
    {
     "title": "Response Results",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bind_responses_total{instance=~\"$instance\"}[120s])",
       "legendFormat": "{{ result }} ({{ instance }})"
      }
     ]
    },
    {
     "title": "Outgoing Queries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bind_resolver_queries_total{instance=~\"$instance\"}[120s])",
       "legendFormat": "{{ view }} / {{ type }} ({{ instance }})"
      }
     ]
    },
    {
     "title": "Queries Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bind_query_duplicates_total{instance=~\"$instance\"}[120s])",
       "legendFormat": "Duplicates ({{ instance }})"
      },
      {
       "expr": "increase(bind_query_errors_total{instance=~\"$instance\"}[120s])",
       "legendFormat": "{{ error }} ({{ instance }})"
      },
      {
       "expr": "increase(bind_query_recursions_total{instance=~\"$instance\"}[120s])",
       "legendFormat": "Recursions ({{ instance }})"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Hits",
     "type": "graph",
     "description": "Number of incoming queries that are answered from cache.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bind_resolver_query_hits[120s])",
       "legendFormat": "{{ view }} / {{ instance }}"
      }
     ]
    },
    {
     "title": "Query Misses",
     "type": "graph",
     "description": "Number of queries that did not have its answers in cache and need resolving.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(bind_resolver_query_misses[120s])",
       "legendFormat": "{{ view }} / {{ instance }}"
      }
     ]
    },
    {
     "title": "Query Hit Ratio",
     "type": "graph",
     "description": "Cache effectiveness, the number of queries that are retrieved from cache divided by the total number of incoming queries.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(bind_resolver_query_hit_ratio[120s])",
       "legendFormat": "{{ view }} ({{ instance }})"
      }
     ]
    },
    {
     "title": "Cache RR Sets",
     "type": "graph",
     "description": "Number of RRsets in cache.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bind_resolver_cache_rrsets{instance=~\"$instance\"}",
       "legendFormat": "{{ view }} / {{ type }} ({{ instance }})"
      }
     ]
    }
   ]
  },
  { "title": "Resolver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "DNSSEC Validation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_dnssec_validation_errors_total{instance=~\"$instance\"}[120s])",
     "legendFormat": "{{ view }} / ValErr ({{ instance }})"
    },
    {
     "expr": "increase(bind_resolver_dnssec_validation_success_total{instance=~\"$instance\"}[120s])",
     "legendFormat": "{{ view }} / {{ result }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Resolver Response Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_response_errors_total{instance=~\"$instance\"}[120s])",
     "legendFormat": "{{ view }} / {{ error }} ({{ instance }})"
    },
    {
     "expr": "increase(bind_resolver_response_lame_total{instance=~\"$instance\"}[120s])",
     "legendFormat": "{{ view }} / LAME ({{ instance }})"
    },
    {
     "expr": "increase(bind_resolver_response_mismatch_total{instance=~\"$instance\"}[120s])",
     "legendFormat": "{{ view }} / MISMATCH ({{ instance }})"
    },
    {
     "expr": "increase(bind_resolver_response_truncated_total{instance=~\"$instance\"}[120s])",
     "legendFormat": "{{ view }} / TRUNCATED ({{ instance }})"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_query_errors_total{instance=~\"$instance\"}[120s])",
     "legendFormat": "{{ view }} / {{ error }} ({{ instance }})"
    },
    {
     "expr": "increase(bind_resolver_query_edns0_errors_total{instance=~\"$instance\"}[120s])",
     "legendFormat": "{{ view }} / EDNS0 ({{ instance }})"
    },
    {
     "expr": "increase(bind_resolver_query_retries_total{instance=~\"$instance\"}[120s])",
     "legendFormat": "{{ view }} / Retry ({{ instance }})"
    }
   ]
  }
 ]
}