{
 "title": "Stork Kea DHCPv6",
 "tags": [
  "kea",
  "stork",
  "dhcp6",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "kea_dhcp6_packets_received_total"
   },
   { "name": "subnet", "label": "Subnet", "query": "kea_dhcp6_na_total" }
  ]
 },
 "panels": [
  {
   "title": "Number of drops of received packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp6_packets_received_total{operation=\"drop\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Actual number of SARR  packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp6_packets_received_total{operation=\"solicit\", instance=~\"$instance\"} or kea_dhcp6_packets_sent_total{operation=\"advertise\", instance=~\"$instance\"}\nor kea_dhcp6_packets_received_total{operation=\"request\", instance=~\"$instance\"} or kea_dhcp6_packets_sent_total{operation=\"reply\", instance=~\"$instance\"}",
     "legendFormat": "{{operation}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Total number of addresses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp6_na_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of addresses assigned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp6_na_assigned_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Total number of prefixes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp6_pd_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of prefixes assigned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp6_pd_assigned_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Subnet addresses utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * kea_dhcp6_na_assigned_total{instance=~\"$instance\", subnet=~\"$subnet\"} / kea_dhcp6_na_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Subnet prefixes utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * kea_dhcp6_pd_assigned_total{instance=~\"$instance\", subnet=~\"$subnet\"} / kea_dhcp6_pd_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of reclaimed addresses per 10min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kea_dhcp6_na_reclaimed_total{instance=~\"$instance\", subnet=~\"$subnet\"}[10m])",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of addresses declined",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp6_addresses_declined_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of addresses declined-reclaimed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp6_addresses_declined_reclaimed_total{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Subnet address utilization (server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "storkserver_subnet_address_utilization{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\""
    }
   ]
  },
  {
   "title": "Subnet pd utilization (server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "storkserver_subnet_pd_utilization{instance=~\"$instance\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{name}}\""
    }
   ]
  },
  {
   "title": "Shared network address utilization (server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "storkserver_shared_network_address_utilization{instance=~\"$instance\"}",
     "legendFormat": "subnet \"{{name}}\""
    }
   ]
  },
  {
   "title": "Shared network pd utilization (server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "storkserver_shared_network_pd_utilization{instance=~\"$instance\"}",
     "legendFormat": "subnet \"{{name}}\""
    }
   ]
  },
  {
   "title": "Machines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storkserver_auth_unauthorized_machine_total{instance=~\"$instance\"}",
     "legendFormat": "unauthorized on {{instance}}"
    },
    {
     "expr": "storkserver_auth_authorized_machine_total{instance=~\"$instance\"}",
     "legendFormat": "authorized on {{instance}}"
    },
    {
     "expr": "storkserver_auth_unreachable_machine_total{instance=~\"$instance\"}",
     "legendFormat": "unreachable on {{instance}}"
    }
   ]
  }
 ]
}