{
 "title": "Stork",
 "description": "An early prototype for Stork dashboad",
 "time": { "from": "2019-09-23T09:53:51.480Z", "to": "2019-09-23T12:00:55.730Z" },
 "panels": [
  {
   "title": "Stork 0.1.0",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "content": "![stork](https://gitlab.isc.org/isc-projects/stork/wikis/uploads/e0ede8b46235eb1c3670bb6528e9fbbe/stork-128x128-transp.png)"
  },
  {
   "title": "BIND 9.11.3",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "content": "![bind9](https://gitlab.isc.org/isc-projects/stork/wikis/uploads/c27b57e43adeb19936bb9b821bb27e1e/Bind_9_Mark_ISC_Blue-128x128-transp.png)"
  },
  {
   "title": "Kea 1.7.0-git",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "content": "![kea](https://gitlab.isc.org/isc-projects/stork/wikis/uploads/d310607da950b64de2a472f7519032af/kea-128x128-transp.png)"
  },
  {
   "title": "Stork: Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_Active" }
   ]
  },
  {
   "title": "BIND: # of queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bind_resolver_queries_total" }
   ]
  },
  {
   "title": "Kea: Assigned addrs",
   "type": "graph",
   "description": "This is a Stork dashboard.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kea_dhcp4_addresses_assigned_total"
    }
   ]
  }
 ]
}