[program:kea-dhcp-ddns]
command=/usr/sbin/kea-dhcp-ddns -c /etc/kea/kea-dhcp-ddns.conf
autostart = true
autorestart = false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
