[eventlistener:process_initializer]
# Use the process initializer to run initialization scripts for application
# processes when they start. The event listener listens for the
# PROCESS_STATE_RUNNING event, which is emitted by supervisorD when a process
# is recognized as fully running. When the event is received, the event
# listener executes the initialization scripts for that process, if they have
# not been executed before. The initialization scripts are expected to be
# located in the /var/lib/process-initializer directory, in a subdirectory
# named after the process.
# The script files must have a shebang.
# The event listener also uses a temporary directory to keep track of which
# processes have already been initialized, so they are preserved across
# container restarts. It writes a file named after the process with a timestamp
# content in the temporary directory when it executes the initialization
# scripts.
command=python3 /usr/lib/process_initializer.py -d /var/lib/process-initializer -t /tmp/process-initializer
events=PROCESS_STATE_RUNNING
stderr_logfile=/var/log/supervisor/process_initializer.err.log
