// This is a basic configuration for the Kea DHCP DDNS daemon.
{

"DhcpDdns":
{
  "ip-address": "127.0.0.1",
  "port": 53001,
  "control-socket": {
      "socket-type": "unix",
      "socket-name": "/var/run/kea/kea-ddns-ctrl-socket"
  },
  "tsig-keys": [],
  "forward-ddns" : {},
  "reverse-ddns" : {},
  "loggers": [
    {
        "name": "kea-dhcp-ddns",
        "output_options": [
            {
                "output": "stdout",
                "pattern": "%-5p %m\n"
            },
            {
                "output": "/var/log/kea/kea-dhcp-ddns.log"
            }
        ],
        "severity": "INFO",
        "debuglevel": 0
    }
  ]
}
}
