#!/bin/sh

set -e

# create folders for storing certs and agent token,
# they should be available to owner ie. stork-agent user
home_dir=/var/lib/stork-agent
mkdir -p -m 700 $home_dir/certs
mkdir -p -m 700 $home_dir/tokens

addgroup -S stork-agent >/dev/null
adduser -h $home_dir -D -S -H -g "Stork Agent User" -G stork-agent stork-agent >/dev/null

# add stork-agent user to bind so it can read its config files
if [ $(getent group bind) ]; then
    addgroup stork-agent bind
fi

# change ownership of all folders and files in home dir to stork-agent user
chown -R stork-agent $home_dir
