#!/bin/sh

set -eu

# Create folders for storing certs and agent token, they should be available
# to owner ie. stork-agent user.
agent_home_dir=/var/lib/stork-agent
mkdir -p "${agent_home_dir}/certs"
mkdir -p "${agent_home_dir}/tokens"
chmod 700 "${agent_home_dir}/certs"
chmod 700 "${agent_home_dir}/tokens"

# Directly retrieve uid and gid in case the user is self-managed
stork_agent_uid=$(getent passwd stork-agent | cut -d: -f3)
stork_agent_gid=$(getent group stork-agent | cut -d: -f3)

# Add stork-agent user to BIND9 group so it can read its config files.
if getent group named > /dev/null; then
    addgroup stork-agent named
fi

# Add stork-agent user to kea so it can read its config files.
if getent group kea > /dev/null; then
    addgroup stork-agent kea
fi

# Change ownership of all folders and files in home dir to stork-agent user.
chown -R "${stork_agent_uid}:${stork_agent_gid}" "${agent_home_dir}"
