package agent

type AgentPaths struct {
	// Paths pointing to agent's key and cert, and CA cert from server,
	// and agent token generated by agent.
	KeyPEMPath      string
	CertPEMPath     string
	RootCAPAth      string
	TokenPath       string
	CredentialsPath string
}

func NewAgentPaths() AgentPaths {
	return AgentPaths{
		KeyPEMPath:      "/var/lib/stork-agent/certs/key.pem",
		CertPEMPath:     "/var/lib/stork-agent/certs/cert.pem",
		RootCAPAth:      "/var/lib/stork-agent/certs/ca.pem",
		TokenPath:       "/var/lib/stork-agent/tokens/agent-token.txt",
		CredentialsPath: "/etc/stork/agent-credentials.json",
	}
}
